spring:
  liquibase:
    defaultSchema: test_schema
  jpa:
    properties:
      hibernate:
        default_schema: test_schema
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_db
    username: test
    password: test
